/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require('nativewind/preset')],
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './features/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#09090b',
        card: '#ffffff',
        cardForeground: '#09090b',
        popover: '#ffffff',
        popoverForeground: '#09090b',
        primary: '#5ea500',
        primaryForeground: '#f7fee7',
        secondary: '#f4f4f5',
        secondaryForeground: '#18181b',
        muted: '#f4f4f5',
        mutedForeground: '#71717b',
        accent: '#f4f4f5',
        accentForeground: '#18181b',
        destructive: '#e7000b',
        border: '#e4e4e7',
        input: '#e4e4e7',
        ring: '#9ae600',
        chart1: '#7bf1a8',
        chart2: '#00c950',
        chart3: '#00a63e',
        chart4: '#008236',
        chart5: '#016630',
        sidebar: '#fafafa',
        sidebarForeground: '#09090b',
        sidebarPrimary: '#5ea500',
        sidebarPrimaryForeground: '#f7fee7',
        sidebarAccent: '#f4f4f5',
        sidebarAccentForeground: '#18181b',
        sidebarBorder: '#e4e4e7',
        sidebarRing: '#9ae600',
      },
      borderRadius: {
        none: '0px',
        sm: '0.125rem',
        DEFAULT: '0.65rem',
        md: '0.65rem',
        lg: 'calc(0.65rem + 4px)',
        xl: 'calc(0.65rem + 8px)',
        full: '9999px',
      },
    },
  },
  plugins: [],
};


